name = "LatticeArrays"
uuid = "41f948cd-8216-4059-8c54-ad7a5f2ef2f3"
authors = ["lkdvos <lukas.devos@ugent.be> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
