name = "LatticeArrays"
uuid = "41f948cd-8216-4059-8c54-ad7a5f2ef2f3"
authors = ["lkdvos <lukas.devos@ugent.be> and contributors"]
version = "1.0.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
HexArrays = "790b99d3-2dbd-4ac5-b9be-633254b365b4"

[compat]
CairoMakie = "0.14"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
